//Type script -> Type script is super set of javascript
// browser understand only html,css, java script. so we need to convert ts(Type script) to js(Java script).
// tsc(type script compiler)tool used to covert(compile) typescript into javascript
 // package.json will be generated by using npm
 // tsconfig.json contain type script compiler configuration. when you run tsc command, it will check the tsconfig.json file.
import {Employee} from "./Employee";
import {EmployeeValidator } from "./EmployeeValidator";
import {address} from "./Employee";
 let a : Number = 20;
 
 let b:string = "Hello";
 
 let c:boolean = true;
 
 let d : String = "Welcome";
 
 
let emp = new Employee("Harish",20,600000,"SE");
console.log(emp.name + "  "+ emp.salary + " "+emp.monthlySalary());
console.log("Address :: "+address);
console.log("Country :: "+Employee.country);
console.log(emp.name + " is valid employee :: "+new EmployeeValidator().validateEmployee(emp));

let emp2 = new Employee("Mahesh",40,800000,"Mechanical");
console.log(Employee.country);
